apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: vhv3vthao-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/vhv3vthao-java-quarkus-gitops